Популярные библиотеки: RxJava 2, Dagger 2, Moxy. Урок 1. Домашняя работа
zhenikaKi/KotlinPopularLibraries pull request #1
Opened 2021-07-28 17:53 UTC by zhenikaKi

2021-07-29 14:01 UTC, PeterBukhal-Geekbrains requested changes
Есть критические замечания. Пока не принимаю.

2021-07-29 14:01 UTC, PeterBukhal-Geekbrains commented on app/src/main/java/ru/kirea/kotlinpopularlibraries/view/CounterView.kt
> +    fun setButtonText(button: CounterModel.Buttons, value: String)
при описании поведения представления лучше отказаться от подробностей реализации, презентеру вовсе необязательно знать что представление отображает счетчик используя кнопки. Если скажем завтра придется поменять реализацию представления и отображать счетчик используя не кнопки, а диалоги, то в этот контракт придется вносить изменения, чего можно было бы легко избежать. Можно просто `showCounter(counter: String)` будет достаточно.

2021-07-29 14:01 UTC, PeterBukhal-Geekbrains commented on app/src/main/java/ru/kirea/kotlinpopularlibraries/model/CounterModel.kt
> +    enum class Buttons(val index: Int) {
цель домашнего задания в том числе уйти от использования индексов, использование которых затрудняет добавление новых счетчиков, так как приводит к необходимости ссылаться на эти индексы как в представлении, так и в презентере. В данном случае лучшим решением будет сделать отдельные методы для отображения во вью и модификации счетчиков в презентере.

2021-07-29 14:01 UTC, PeterBukhal-Geekbrains commented on app/src/main/java/ru/kirea/kotlinpopularlibraries/presenter/CounterPresenter.kt
>      private val counterModel = CounterModel()
модель следует передать в конструкторе, что бы обеспечить возможность подмены для тестирования, а так же сделать эти зависимости недоступными для изменения из вне, то есть инкапсулировать их.

2021-07-29 15:13 UTC, zhenikaKi commented on app/src/main/java/ru/kirea/kotlinpopularlibraries/presenter/CounterPresenter.kt
>      private val counterModel = CounterModel()
И интерфейс view, и модель в конструкторе передавать?

2021-07-29 15:33 UTC, zhenikaKi commented
@PeterBukhal-Geekbrains, подправил все замечания кроме одного: Передача модели в конструктор презентора. Это получается из CounterActivity мы инициализируем презентер, передавая в него интерфейс для взаимодействия с CounterActivity и саму модель. А разве CounterActivity должна что-то знать о моделе?

2021-07-29 15:38 UTC, PeterBukhal-Geekbrains commented
> @PeterBukhal-Geekbrains, подправил все замечания кроме одного: Передача модели в конструктор презентора. Это получается из CounterActivity мы инициализируем презентер, передавая в него интерфейс для взаимодействия с CounterActivity и саму модель. А разве CounterActivity должна что-то знать о моделе?

получается, что так. мы этот момент поправим когда дойдем до dagger2 да и сегодня на вебинаре посмотрим что с этим делать можно еще. в целом это особенность android sdk

2021-07-29 15:42 UTC, zhenikaKi commented
> > @PeterBukhal-Geekbrains, подправил все замечания кроме одного: Передача модели в конструктор презентора. Это получается из CounterActivity мы инициализируем презентер, передавая в него интерфейс для взаимодействия с CounterActivity и саму модель. А разве CounterActivity должна что-то знать о моделе?
> 
> получается, что так. мы этот момент поправим когда дойдем до dagger2 да и сегодня на вебинаре посмотрим что с этим делать можно еще. в целом это особенность android sdk

Запушил еще коммит, в котором передаю модель в конструктор презентора.

2021-07-29 15:49 UTC, PeterBukhal-Geekbrains commented
@zhenikaKi отправь повторно работу на проверку на платформе.

2021-07-29 15:57 UTC, zhenikaKi commented
> @zhenikaKi отправь повторно работу на проверку на платформе.

Готово

2021-08-01 12:19 UTC, PeterBukhal-Geekbrains approved these changes
Отлично, задание выполнено, замечаний нет.

2021-08-01 16:42 UTC, merged